#' Synthesise a single (optionally nested / longitudinal) table
#'
#' Generate synthetic data for one table, working natively in long format. The
#' `structure` formula declares the nesting hierarchy (e.g.
#' `~ id / visit / test_number`) so repeated-measures and nested designs are kept
#' without pivoting to wide format.
#'
#' The default (Track A) engine is sequential conditional synthesis in the
#' synthpop lineage: the unit identifier is regenerated by resampling whole
#' units (preserving realistic per-unit block sizes), and each remaining variable
#' is synthesised in turn from a model fitted on the real data, conditioning on
#' the structural columns and everything synthesised before it. With
#' `method = "cart"` each draw comes from the matching leaf of a regression /
#' classification tree, so marginal and conditional distributions are preserved
#' without distributional assumptions. Track A carries **no** formal privacy
#' guarantee.
#'
#' Columns that are constant within every real unit (baseline covariates such as
#' age or sex) are detected automatically and synthesised **once per unit**, then
#' broadcast across that unit's rows, so a synthetic subject stays internally
#' consistent. Time-varying columns are synthesised with an initial-state model
#' (first row of each unit) plus a Markov transition model that conditions on the
#' previous row within the unit (lag-1 predictors), so autocorrelation across
#' visits is preserved. The number of rows per unit is drawn from the learned
#' count distribution and the structural-index sequence is regenerated for each
#' synthetic unit.
#'
#' Supplying `constraints` (see [rule()]) keeps only synthetic units whose rows
#' satisfy every rule, regenerating until enough valid units are collected — so
#' logical and within-unit temporal constraints are honoured without breaking
#' the nested structure.
#'
#' Passing `privacy = dp_control(...)` selects differentially private synthesis
#' (Track B), which is a later roadmap phase.
#'
#' @param data A `data.frame` in long format.
#' @param structure A one-sided formula giving the nesting hierarchy, e.g.
#'   `~ id / visit`. The first term is the unit identifier.
#' @param method Synthesis method, `"cart"` (default) or `"sample"`, applied per
#'   variable unless overridden in `tuning`.
#' @param constraints Optional [rule()] (or list of rules) the synthetic data
#'   must satisfy. Enforced by rejection sampling at the unit grain (see
#'   [rule()]); `constraint_max_tries` in [synth_control()] bounds the effort.
#' @param tuning A [synth_control()] object.
#' @param privacy `NULL` for Track A, or a [dp_control()] object for Track B.
#' @param m Number of synthetic datasets to produce.
#' @param seed Optional integer seed for reproducibility.
#' @param ... Reserved for future use.
#'
#' @return A `synth_result` object. Use [as.data.frame()] (for `m == 1`) or
#'   `$syn` to get the synthetic data.
#' @export
#' @examples
#' df <- data.frame(
#'   id    = rep(1:20, each = 2),
#'   visit = rep(1:2, times = 20),
#'   age   = rep(round(rnorm(20, 60, 8)), each = 2),
#'   sbp   = round(rnorm(40, 130, 15))
#' )
#' res <- synth(df, structure = ~ id / visit, seed = 1)
#' head(as.data.frame(res))
synth <- function(data,
                  structure,
                  method = "cart",
                  constraints = NULL,
                  tuning = synth_control(),
                  privacy = NULL,
                  m = 1,
                  seed = NULL,
                  ...) {
  validate_synth_inputs(data, structure, tuning, privacy, m)

  if (!is.null(privacy)) {
    stop(paste0("synth(): differentially private synthesis (Track B) is not ",
                "implemented yet (Phase 7). See CLAUDE.md roadmap."),
         call. = FALSE)
  }
  rules <- normalise_constraints(constraints, data)

  st <- parse_structure(structure, data)
  if (!is.null(seed)) set.seed(seed)

  fixed_cols <- st$nested
  synth_cols <- setdiff(names(data), st$vars)

  vs <- tuning$visit_sequence
  if (!is.null(vs)) {
    bad <- setdiff(vs, synth_cols)
    if (length(bad)) {
      stop(sprintf(
        "`visit_sequence` names non-synthesisable column(s): %s",
        paste(bad, collapse = ", ")
      ), call. = FALSE)
    }
    synth_cols <- c(intersect(vs, synth_cols), setdiff(synth_cols, vs))
  }

  methods <- resolve_methods(method, tuning$method, synth_cols)

  subj_cols <- subject_level_cols(data, st$id, synth_cols)
  time_cols <- setdiff(synth_cols, subj_cols)   # keeps synth_cols order

  gen_one <- function()
    synthesise_once(data, st, subj_cols, time_cols, fixed_cols, methods, tuning)
  syns <- lapply(seq_len(m), function(i) {
    if (is.null(rules)) gen_one()
    else apply_constraints(gen_one, st$id, rules, tuning)
  })
  syn <- if (m == 1L) syns[[1L]] else syns

  new_synth_result(
    syn = syn, m = as.integer(m), n = nrow(data), method = methods,
    structure = structure, visit_sequence = synth_cols, fixed = fixed_cols,
    subject = subj_cols, privacy = NULL, seed = seed, call = match.call()
  )
}
